import { Metadata } from "next";
import { Download } from "lucide-react";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "amadorgabriel - Desenvolvedor de Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ptBR">
      <body
        className={`${inter.variable} relative antialiased w-screen border-t-3 border-t-yellow-500 overflow-x-hidden`}
      >
        <a
          href="/resume.pdf"
          target="_blank"
          className="absolute flex items-center top-6 right-10 md:right-28  font-semibold py-1 px-4 rounded-[4px] text-yellow-500 hover:bg-slate-200"
        >
          <Download size={18} className="mr-2" />
          Baixar como  PDF
        </a>

        <main className="w-full flex justify-center mb-8">{children}</main>
      </body>
    </html>
  );
}
